spring:
  application:
    name: countries-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

