spring:
  application:
    name: client-rus
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
