services:
  mysql-db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3037:3036"
    networks:
      - mysql
    restart: unless-stopped

networks:
  mysql:
    driver: bridge