version: "3.9" # optional since v1.27.0
services:
  # Postgres database
  postgresdb:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zsecsq11
      - POSTGRES_DB=spring_test
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  postgres_admin:
    image: dpage/pgadmin4:6.14
    depends_on:
      - postgresdb
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.en
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

  # Main app
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: spring_app
    ports:
      - '8080:8080'
    depends_on:
      - postgresdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/spring_test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=zsecsq11
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

